-------- REPRESENTACION DEL FLUJO DE DATOS --------

---DATA CRUDA

SELECT * FROM raw_customers;
SELECT * FROM raw_employees;
SELECT * FROM raw_expenses ;
SELECT * FROM raw_payments;
SELECT * FROM raw_subscriptions;
SELECT * FROM raw_transactions;

---DATA SILVER

SELECT * FROM SILVER.S_CUSTOMERS;
SELECT * FROM SILVER.S_EMPLOYEES;
SELECT * FROM SILVER.S_EXPENSES;
SELECT * FROM SILVER.S_PAYMENTS;
SELECT * FROM SILVER.S_SUBSCRIPTIONS; --Se filtraron 741 registros por FECHA FIN INVALIDA (MENOR AL INICIO)
SELECT * FROM SILVER.S_TRANSACTIONS;
SELECT * FROM SILVER.S_TABLA_ERROR;

--- DATA GOLD TABLES AND VIES

SELECT * FROM GOLD.FACT_CASHFLOW;
SELECT * FROM GOLD.FACT_MRR_MONTHLY;
SELECT * FROM GOLD.DIM_DAT;
SELECT * FROM GOLD.VW_DASHBOARD_MRR;
SELECT * FROM GOLD.VW_DASHBOARD_CAC;
SELECT * FROM GOLD.VW_DASHBOARD_CASHFLOW;





