
--CALCULOS CON LAS CAPAS SILVER Y GOLD PARA GARANTIZAR LA INTEGRIDAD DE LOS DATOS

--¿Cuál fue el MRR total de agosto de 2024?

SELECT SUM(G_MONTHLY_PRICE) as MRR_AUG_2024
FROM GOLD.FACT_MRR_MONTHLY
WHERE G_MONTHS_ADD = '2024-08-01';

--R/ 56600


--¿Cuántos clientes nuevos se registraron durante el primer trimestre de 2024?

SELECT COUNT(S_CUSTOMER_ID) as NEW_CLIENTS_Q1
FROM SILVER.S_CUSTOMERS
WHERE S_REGISTRATION_TIMESTAMP::DATE BETWEEN '2024-01-01' AND '2024-03-31';

--R/ 235


--¿Cuál fue el total de gastos de marketing durante el primer semestre de 2024?

SELECT SUM(S_AMOUNT_USD) as MARKETING_EXPENSES_H1
FROM SILVER.S_EXPENSES
WHERE S_CATEGORY = 'MARKETING'
  AND S_EXPENSE_DATE::DATE BETWEEN '2024-01-01' AND '2024-06-30';

--R 736200


--¿Cuál fue el Free Cash Flow (FCF) en diciembre de 2024?

SELECT SUM(G_NET_AMOUNT_USD) as FCF_DEC_2024
FROM GOLD.FACT_CASHFLOW
WHERE G_FLOW_DATE::DATE BETWEEN '2024-12-01' AND '2024-12-31';

--R/-533861


--¿Cuál fue el país con mayor ingreso total durante 2024?

SELECT t.S_COUNTRY, SUM(p.S_AMOUNT_USD) as TOTAL_REVENUE
FROM SILVER.S_PAYMENTS p
LEFT JOIN SILVER.S_TRANSACTIONS t ON p.S_TRANSACTION_ID = t.S_TRANSACTION_ID
WHERE S_PAYMENT_DATE::DATE BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY 1 ORDER BY 2 DESC LIMIT 1;

--R/UNITED STATES = 268366


--¿Cuál fue el CAC promedio anual considerando gastos de marketing y nuevos clientes?

SELECT
    (SELECT SUM(S_AMOUNT_USD) FROM SILVER.S_EXPENSES WHERE S_CATEGORY = 'MARKETING' AND YEAR(S_EXPENSE_DATE) = 2024) /
    (SELECT COUNT(S_CUSTOMER_ID) FROM SILVER.S_CUSTOMERS WHERE YEAR(S_REGISTRATION_TIMESTAMP) = 2024)
as ANNUAL_AVG_CAC;

--R/1499.352




